---

- name: Ensure python-pycurl is installed
  apt: pkg=python-pycurl state=installed

- name: Ensure Elasticsearch apt signing key is installed
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Ensure Logstash 1.3.x repository is installed
  apt_repository: repo="deb http://packages.elasticsearch.org/logstash/1.3/debian stable main" update_cache=yes

- name: Ensure logstash is installed
  apt: pkg={{item}} state=installed
  with_items:
    - openjdk-7-jre
    - logstash

- name: Ensure logstash service config is in place
  copy: src=logstash_default dest=/etc/default/logstash
  notify:
    - restart logstash

- name: Ensure logstash config is in place
  copy: src=logstash.conf dest=/etc/logstash/conf.d/logstash.conf
  notify:
    - restart logstash

- name: Ensure SSL certificates have the correct directories
  file: path=/etc/pki/tls/{{item}} owner=root group=root mode=0755 state=directory
  with_items:
    - certs
    - private
  notify:
    - restart logstash

- name: Ensure logstash-forwarder has its SSL certificate
  copy: src=certs/logstash-forwarder.crt dest=/etc/pki/tls/certs/logstash-forwarder.crt owner=root group=root mode=0755
  notify:
    - restart logstash

- name: Ensure logstash-forwarder has its SSL private key
  copy: src=certs/logstash-forwarder.key dest=/etc/pki/tls/private/logstash-forwarder.key owner=root group=root mode=0755
  notify:
    - restart logstash
